export const ActionTypes = {
  CURRENT_PAGE: "CURRENT_PAGE",
  SET_STEP: "SET_STEP",
  SHOW_VERIFY_EMAIL: "SHOW_VERIFY_EMAIL",
  SET_CURRENT_BRANCH: "SET_CURRENT_BRANCH",
  SET_CATEGORIES: "SET_CATEGORIES",
};
