export const Products = [
  {
    code: 1,
    name: "Leonanie Mountfort",
    quantity: 26,
    category: "Wine",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
  {
    code: 2,
    name: "Iosep Anand",
    quantity: 49,
    category: "Cosmetics",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
  {
    code: 3,
    name: "Leonanie Mountfort",
    quantity: 26,
    category: "Wine",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
  {
    code: 4,
    name: "Iosep Anand",
    quantity: 49,
    category: "Cosmetics",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
  {
    code: 5,
    name: "Leonanie Mountfort",
    quantity: 26,
    category: "Wine",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
  {
    code: 6,
    name: "Iosep Anand",
    quantity: 49,
    category: "Cosmetics",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
  {
    code: 7,
    name: "Leonanie Mountfort",
    quantity: 26,
    category: "Wine",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
  {
    code: 8,
    name: "Iosep Anand",
    quantity: 49,
    category: "Cosmetics",
    creator: "Sarah Ali",
    date: "30 Dec 2018",
  },
];
